# For more information: https://laravel.com/docs/sail
version: "3"
services:
  selenium:
    image: "selenium/standalone-chrome"
    volumes:
      - "./docker/selenium:/dev/shm"
    networks:
      - sail

volumes:
  sail-pgsql:
    driver: local
