# For more information: https://laravel.com/docs/sail
version: "3"
services:
    app:
        image: erstevn/sail-php:latest
        build:
            context: ./docker/php/build
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
            - ./docker/php/config/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
        networks:
            - sail
        expose:
            - "9000"
        container_name: sail-app
    nginx:
        image: erstevn/sail-nginx:latest
        build:
            context: "./docker/nginx/build"
        depends_on:
            - app
        volumes:
            - ./docker/nginx/ssl/:/etc/nginx/ssl
            - ./:/var/www/html:cached
            - ./docker/logs/nginx/:/var/log/nginx
            - ./docker/nginx/sites/:/etc/nginx/sites-available
        ports:
            - "${FORWARD_NGINX_HTTPS_PORT:-443}:443"
            - "${FORWARD_NGINX_HTTP_PORT:-80}:80"
        networks:
            - sail
        container_name: sail-nginx
    meilisearch:
        image: "getmeili/meilisearch:latest"
        expose:
            - "7700"
        volumes:
            - sail-meilisearch:/meili_data
            - ./docker/meilisearch/dump/:/meili_data/dumps:rw
        networks:
            - sail
        environment:
            - MEILI_MASTER_KEY=${MEILISEARCH_KEY:-meilisearch-key}
            - MEILI_IMPORT_DUMP=/meili_data/dumps/meili-dump.dump
            - MEILI_IGNORE_DUMP_IF_DB_EXISTS=true
            - MEILI_IGNORE_MISSING_DUMP=true
        healthcheck:
            test:
                ["CMD", "wget", "--no-verbose", "--spider", "${APP_URL}/health"]
            retries: 3
            timeout: 5s
        container_name: sail-meilisearch
networks:
    sail:
        driver: bridge
volumes:
    sail-meilisearch:
        driver: local
    sail-redis:
        driver: local
