# For more information: https://laravel.com/docs/sail
version: "3"
services:
    app:
        image: erstevn/sail-php:latest
        build:
            context: ./docker/php/build
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ./:/var/www/html${APP_CONTAINER_FLAG}
            - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
            - ./docker/php/config/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
        networks:
            - sail
        expose:
            - "9000"
        container_name: sail-app
    nginx:
        image: erstevn/sail-nginx:latest
        build:
            context: "./docker/nginx/build"
        depends_on:
            - app
        volumes:
            - ./docker/nginx/ssl/:/etc/nginx/ssl
            - ./:/var/www/html${APP_CONTAINER_FLAG}
            - ./docker/logs/nginx/:/var/log/nginx
            - ./docker/nginx/sites/:/etc/nginx/sites-available
        ports:
            # port mappings, host to docker
            - "${NGINX_HOST_HTTPS_PORT:-443}:443"
            - "${NGINX_HOST_HTTP_PORT:-80}:80"
        networks:
            - sail
        container_name: sail-nginx
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
